### ISSUE TITLE
Slack webhook exposure

### ISSUE THREAD

**Issue by tillson** [solacese/pubsubplusmonitor-docker#1]
Howdy,
There's a Slack webhook API endpoint exposed at
https://github.com/solacese/pubsubplusmonitor-docker/blob/20291adcc81ea2b2b6a1828929a25e929a8e6573/my_alert_actions.sh.
This grants write access to the corresponding Slack channel.

**Comment by Ushnash** [comment]
Oops! thanks @tillson !
